import Foundation
import CoreImage
import CoreImage.CIFilterBuiltins
import AppKit

// Generates QR PNGs with the system CoreImage encoder — no dependency, no
// network, no third-party service holding the code hostage.
//
//   swift tools/make-qr.swift <url> <output.png> [pixelSize]
//
// Verify what you generated by decoding it back with tools/read-qr.swift
// rather than trusting that the right string went in.

let args = CommandLine.arguments
guard args.count >= 3 else {
    print("usage: swift make-qr.swift <url> <output.png> [pixelSize]")
    exit(1)
}

let payload = args[1]
let outPath = args[2]
let pixelSize = args.count > 3 ? (Int(args[3]) ?? 720) : 720

let filter = CIFilter.qrCodeGenerator()
filter.message = Data(payload.utf8)
// H = highest error correction: survives a logo overlay, a fold, a bad
// projector, and a phone camera at an angle across a room.
filter.correctionLevel = "H"

guard let output = filter.outputImage else {
    print("failed to generate")
    exit(1)
}

// Scale by an integer factor so module edges stay crisp instead of blurring.
let scale = max(1, CGFloat(pixelSize) / output.extent.width)
let scaled = output.transformed(by: CGAffineTransform(scaleX: scale, y: scale))

let context = CIContext()
guard let cg = context.createCGImage(scaled, from: scaled.extent) else {
    print("failed to rasterise")
    exit(1)
}

let rep = NSBitmapImageRep(cgImage: cg)
guard let png = rep.representation(using: .png, properties: [:]) else {
    print("failed to encode png")
    exit(1)
}

try png.write(to: URL(fileURLWithPath: outPath))
print("wrote \(outPath)  \(Int(scaled.extent.width))x\(Int(scaled.extent.height))  <- \(payload)")
